# Generated by Django 5.2.7 on 2025-10-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state_id', models.IntegerField(default=1)),
                ('text', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('revealed', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('round_question', models.CharField(default='Pregunta de la ronda', max_length=255)),
                ('round_total_points', models.IntegerField(default=0)),
                ('strikes', models.IntegerField(default=0)),
                ('active_team', models.CharField(blank=True, max_length=10, null=True)),
                ('buzzers_locked', models.BooleanField(default=True)),
            ],
        ),
    ]
